/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeletionRouteImport } from './routes/deletion'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QSlugRouteImport } from './routes/q.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AppUtmsRouteImport } from './routes/_app/utms'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppReunioesRouteImport } from './routes/_app/reunioes'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppOrganizadorRouteImport } from './routes/_app/organizador'
import { Route as AppMulticanalRouteImport } from './routes/_app/multicanal'
import { Route as AppMetricasRouteImport } from './routes/_app/metricas'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCriativosRouteImport } from './routes/_app/criativos'
import { Route as AppConfigRouteImport } from './routes/_app/config'
import { Route as AppCobrancasRouteImport } from './routes/_app/cobrancas'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppCampanhasRouteImport } from './routes/_app/campanhas'
import { Route as AppAutomacoesRouteImport } from './routes/_app/automacoes'
import { Route as AppAgenteRouteImport } from './routes/_app/agente'
import { Route as AppMetricasGraficoRouteImport } from './routes/_app/metricas.grafico'
import { Route as AppClientesClientIdRouteImport } from './routes/_app/clientes.$clientId'
import { Route as AppCampanhasGraficoRouteImport } from './routes/_app/campanhas.grafico'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletionRoute = DeletionRouteImport.update({
  id: '/deletion',
  path: '/deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QSlugRoute = QSlugRouteImport.update({
  id: '/q/$slug',
  path: '/q/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUtmsRoute = AppUtmsRouteImport.update({
  id: '/utms',
  path: '/utms',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppReunioesRoute = AppReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizadorRoute = AppOrganizadorRouteImport.update({
  id: '/organizador',
  path: '/organizador',
  getParentRoute: () => AppRoute,
} as any)
const AppMulticanalRoute = AppMulticanalRouteImport.update({
  id: '/multicanal',
  path: '/multicanal',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricasRoute = AppMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCriativosRoute = AppCriativosRouteImport.update({
  id: '/criativos',
  path: '/criativos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppCobrancasRoute = AppCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteRoute = AppAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricasGraficoRoute = AppMetricasGraficoRouteImport.update({
  id: '/grafico',
  path: '/grafico',
  getParentRoute: () => AppMetricasRoute,
} as any)
const AppClientesClientIdRoute = AppClientesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppCampanhasGraficoRoute = AppCampanhasGraficoRouteImport.update({
  id: '/grafico',
  path: '/grafico',
  getParentRoute: () => AppCampanhasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deletion': typeof DeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/agente': typeof AppAgenteRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/campanhas': typeof AppCampanhasRouteWithChildren
  '/clientes': typeof AppClientesRouteWithChildren
  '/cobrancas': typeof AppCobrancasRoute
  '/config': typeof AppConfigRoute
  '/criativos': typeof AppCriativosRoute
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/metricas': typeof AppMetricasRouteWithChildren
  '/multicanal': typeof AppMulticanalRoute
  '/organizador': typeof AppOrganizadorRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/reunioes': typeof AppReunioesRoute
  '/upload': typeof AppUploadRoute
  '/utms': typeof AppUtmsRoute
  '/p/$slug': typeof PSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/campanhas/grafico': typeof AppCampanhasGraficoRoute
  '/clientes/$clientId': typeof AppClientesClientIdRoute
  '/metricas/grafico': typeof AppMetricasGraficoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deletion': typeof DeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/agente': typeof AppAgenteRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/campanhas': typeof AppCampanhasRouteWithChildren
  '/clientes': typeof AppClientesRouteWithChildren
  '/cobrancas': typeof AppCobrancasRoute
  '/config': typeof AppConfigRoute
  '/criativos': typeof AppCriativosRoute
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/metricas': typeof AppMetricasRouteWithChildren
  '/multicanal': typeof AppMulticanalRoute
  '/organizador': typeof AppOrganizadorRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/reunioes': typeof AppReunioesRoute
  '/upload': typeof AppUploadRoute
  '/utms': typeof AppUtmsRoute
  '/p/$slug': typeof PSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/campanhas/grafico': typeof AppCampanhasGraficoRoute
  '/clientes/$clientId': typeof AppClientesClientIdRoute
  '/metricas/grafico': typeof AppMetricasGraficoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/deletion': typeof DeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/agente': typeof AppAgenteRoute
  '/_app/automacoes': typeof AppAutomacoesRoute
  '/_app/campanhas': typeof AppCampanhasRouteWithChildren
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/cobrancas': typeof AppCobrancasRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/criativos': typeof AppCriativosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/metricas': typeof AppMetricasRouteWithChildren
  '/_app/multicanal': typeof AppMulticanalRoute
  '/_app/organizador': typeof AppOrganizadorRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/reunioes': typeof AppReunioesRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/utms': typeof AppUtmsRoute
  '/p/$slug': typeof PSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/_app/campanhas/grafico': typeof AppCampanhasGraficoRoute
  '/_app/clientes/$clientId': typeof AppClientesClientIdRoute
  '/_app/metricas/grafico': typeof AppMetricasGraficoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deletion'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/agente'
    | '/automacoes'
    | '/campanhas'
    | '/clientes'
    | '/cobrancas'
    | '/config'
    | '/criativos'
    | '/dashboard'
    | '/integrations'
    | '/metricas'
    | '/multicanal'
    | '/organizador'
    | '/relatorios'
    | '/reunioes'
    | '/upload'
    | '/utms'
    | '/p/$slug'
    | '/q/$slug'
    | '/campanhas/grafico'
    | '/clientes/$clientId'
    | '/metricas/grafico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deletion'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/agente'
    | '/automacoes'
    | '/campanhas'
    | '/clientes'
    | '/cobrancas'
    | '/config'
    | '/criativos'
    | '/dashboard'
    | '/integrations'
    | '/metricas'
    | '/multicanal'
    | '/organizador'
    | '/relatorios'
    | '/reunioes'
    | '/upload'
    | '/utms'
    | '/p/$slug'
    | '/q/$slug'
    | '/campanhas/grafico'
    | '/clientes/$clientId'
    | '/metricas/grafico'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/deletion'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_app/agente'
    | '/_app/automacoes'
    | '/_app/campanhas'
    | '/_app/clientes'
    | '/_app/cobrancas'
    | '/_app/config'
    | '/_app/criativos'
    | '/_app/dashboard'
    | '/_app/integrations'
    | '/_app/metricas'
    | '/_app/multicanal'
    | '/_app/organizador'
    | '/_app/relatorios'
    | '/_app/reunioes'
    | '/_app/upload'
    | '/_app/utms'
    | '/p/$slug'
    | '/q/$slug'
    | '/_app/campanhas/grafico'
    | '/_app/clientes/$clientId'
    | '/_app/metricas/grafico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DeletionRoute: typeof DeletionRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  PSlugRoute: typeof PSlugRoute
  QSlugRoute: typeof QSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deletion': {
      id: '/deletion'
      path: '/deletion'
      fullPath: '/deletion'
      preLoaderRoute: typeof DeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$slug': {
      id: '/q/$slug'
      path: '/q/$slug'
      fullPath: '/q/$slug'
      preLoaderRoute: typeof QSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/utms': {
      id: '/_app/utms'
      path: '/utms'
      fullPath: '/utms'
      preLoaderRoute: typeof AppUtmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reunioes': {
      id: '/_app/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AppReunioesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizador': {
      id: '/_app/organizador'
      path: '/organizador'
      fullPath: '/organizador'
      preLoaderRoute: typeof AppOrganizadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/multicanal': {
      id: '/_app/multicanal'
      path: '/multicanal'
      fullPath: '/multicanal'
      preLoaderRoute: typeof AppMulticanalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metricas': {
      id: '/_app/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AppMetricasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/criativos': {
      id: '/_app/criativos'
      path: '/criativos'
      fullPath: '/criativos'
      preLoaderRoute: typeof AppCriativosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cobrancas': {
      id: '/_app/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof AppCobrancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automacoes': {
      id: '/_app/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agente': {
      id: '/_app/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AppAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metricas/grafico': {
      id: '/_app/metricas/grafico'
      path: '/grafico'
      fullPath: '/metricas/grafico'
      preLoaderRoute: typeof AppMetricasGraficoRouteImport
      parentRoute: typeof AppMetricasRoute
    }
    '/_app/clientes/$clientId': {
      id: '/_app/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof AppClientesClientIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/campanhas/grafico': {
      id: '/_app/campanhas/grafico'
      path: '/grafico'
      fullPath: '/campanhas/grafico'
      preLoaderRoute: typeof AppCampanhasGraficoRouteImport
      parentRoute: typeof AppCampanhasRoute
    }
  }
}

interface AppCampanhasRouteChildren {
  AppCampanhasGraficoRoute: typeof AppCampanhasGraficoRoute
}

const AppCampanhasRouteChildren: AppCampanhasRouteChildren = {
  AppCampanhasGraficoRoute: AppCampanhasGraficoRoute,
}

const AppCampanhasRouteWithChildren = AppCampanhasRoute._addFileChildren(
  AppCampanhasRouteChildren,
)

interface AppClientesRouteChildren {
  AppClientesClientIdRoute: typeof AppClientesClientIdRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesClientIdRoute: AppClientesClientIdRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppMetricasRouteChildren {
  AppMetricasGraficoRoute: typeof AppMetricasGraficoRoute
}

const AppMetricasRouteChildren: AppMetricasRouteChildren = {
  AppMetricasGraficoRoute: AppMetricasGraficoRoute,
}

const AppMetricasRouteWithChildren = AppMetricasRoute._addFileChildren(
  AppMetricasRouteChildren,
)

interface AppRouteChildren {
  AppAgenteRoute: typeof AppAgenteRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppCampanhasRoute: typeof AppCampanhasRouteWithChildren
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppCobrancasRoute: typeof AppCobrancasRoute
  AppConfigRoute: typeof AppConfigRoute
  AppCriativosRoute: typeof AppCriativosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppMetricasRoute: typeof AppMetricasRouteWithChildren
  AppMulticanalRoute: typeof AppMulticanalRoute
  AppOrganizadorRoute: typeof AppOrganizadorRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppReunioesRoute: typeof AppReunioesRoute
  AppUploadRoute: typeof AppUploadRoute
  AppUtmsRoute: typeof AppUtmsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgenteRoute: AppAgenteRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppCampanhasRoute: AppCampanhasRouteWithChildren,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppCobrancasRoute: AppCobrancasRoute,
  AppConfigRoute: AppConfigRoute,
  AppCriativosRoute: AppCriativosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppMetricasRoute: AppMetricasRouteWithChildren,
  AppMulticanalRoute: AppMulticanalRoute,
  AppOrganizadorRoute: AppOrganizadorRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppReunioesRoute: AppReunioesRoute,
  AppUploadRoute: AppUploadRoute,
  AppUtmsRoute: AppUtmsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DeletionRoute: DeletionRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  PSlugRoute: PSlugRoute,
  QSlugRoute: QSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
