// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

function createSupabaseClient() {
  // Forçar as credenciais oficiais do Supabase do Trabalho (xudumzedcxuuhxokissm)
  // para garantir a sincronização imediata no Lovable Cloud e local.
  const SUPABASE_URL = "https://xudumzedcxuuhxokissm.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_KVptQYNLCFSjqmUYJcGmrQ_WurR5l_p";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

